services:
    app:
        image: go-backend:latest
        container_name: go-backend
        volumes:
            - .:/app
            - go-mod:/go/pkg/mod
            - go-cache:/root/.cache/go-build
        ports:
            - "8080:8080"
        env_file:
            - .env
        depends_on:
            - postgres
            - redis
        command: >
            sh -c "goose -dir /app/migration postgres 'postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=${DB_SSL_MODE}' up &&
            air -c .air.toml"

    web:
        image: node:20-alpine
        container_name: web
        working_dir: /app
        command: sh -c "npm install && npm run dev"
        volumes:
            - ./web:/app
        ports:
            - "5173:5173"

    postgres:
        image: postgres:17.4
        restart: always
        container_name: postgres
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - "${DB_PORT}:5432"

    redis:
        image: redis:7-alpine
        restart: always
        container_name: redis
        command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - redis_data:/data

volumes:
    db:
    redis_data:
    go-mod:
    go-cache:
