services:
    postgres:
        image: postgres:17.4
        restart: always
        container_name: postgres
        environment:
            POSTGRES_HOST: ${DB_HOST}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_PORT: ${DB_PORT}
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - "${DB_PORT}:5432"
    redis:
        image: redis:7-alpine
        restart: always
        container_name: redis
        command: [
                "redis-server",
                "--requirepass",
                "${REDIS_PASSWORD}",
                # You can add persistence options here if needed
                # "--save 60 1",
                # "--appendonly yes",
            ]
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - redis_data:/data

volumes:
    db:
    redis_data:
