# Dockerfile.dev
FROM golang:1.25.1-alpine

# Install tools
RUN apk add --no-cache git curl bash && \
    go install github.com/air-verse/air@v1.63.0

WORKDIR /app

# Install dependencies first for caching
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the source
COPY . .

# Run with Air using your config
CMD ["air", "-c", ".air.toml"]
