services:
    postgres:
        image: postgres:17.4
        restart: always
        container_name: postgres
        environment:
            POSTGRES_HOST: ${DB_HOST}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_PORT: ${DB_PORT}
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - "${DB_PORT}:5432"

volumes:
    db:
