services:
    # PostgreSQL database
    postgres:
        image: postgres:17.4
        restart: always
        container_name: postgres-local
        env_file: .env.local
        volumes:
            - echo_template_db_local:/var/lib/postgresql/data
        ports:
            - "127.0.0.1:5432:5432"
        healthcheck:
            test:
                ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
            interval: 5s
            timeout: 5s
            retries: 10

    # Redis cache
    redis:
        image: redis:7-alpine
        restart: always
        container_name: redis-local
        env_file: .env.local
        command: sh -c 'redis-server --requirepass "$$REDIS_PASSWORD"'
        ports:
            - "127.0.0.1:6379:6379"
        volumes:
            - echo_template_redis_local:/data

    # Database migration service
    migration:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.migration
        container_name: migration-local
        volumes:
            - ../migration:/app/migration
        env_file: .env.local
        restart: "no"
        depends_on:
            postgres:
                condition: service_healthy

    app:
        image: echo_template:local
        container_name: app-local
        volumes:
            - ..:/app
        ports:
            - "127.0.0.1:8080:8080"
        env_file: .env.local
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_started
            migration:
                condition: service_completed_successfully

    web:
        image: node:20-alpine
        container_name: web-local
        working_dir: /app
        command: sh -c "npm install && npm run dev"
        volumes:
            - ../web:/app
        ports:
            - "5173:5173"

volumes:
    migration:
    echo_template_db_local:
    echo_template_redis_local:
