# Dockerfile local
FROM golang:1.25.1-alpine

RUN apk add --no-cache git curl bash

# Install air
RUN go install github.com/air-verse/air@v1.63.0

WORKDIR /app

# Install dependencies first for caching
COPY go.mod go.sum ./
RUN go mod download

# Copy source
COPY . .

CMD ["air", "-c", ".air.toml"]
