// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int64
	Name      string
	Email     string
	Phone     sql.NullString
	Role      string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDeleted bool
}
